
environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "6"
install:
  - npm install -g npm
  - npm install
  - npm install --dev-save mocha chai supertest
test_script:
  - ./node_modules/.bin/mocha
 